---
name: CI

on:
  pull_request:
  push:


concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  ruby:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - '2.5.3'
          - '2.7.4'
          - '3.0.2'
        rails_version:
          - '6.0.3.7'
          - '6.0.4.8'
          - '6.1.6'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}
      - name: Run tests
        run: bundle exec rake
